### ISSUE TITLE
Build Shaka Packager

### ISSUE THREAD

**Issue by dmfrey** [thecount2a/mythtv-stream-mpeg-dash#1]
What was the specific command for building?

    ninja -C out/Release

What from the results do you copy to the `ffmpeg` directory?  Is it all the files in `out/Release`?

**Comment by thecount2a** [comment]
Yes, the file you're looking for is called "packager"

Sorry, that is not clear in my instructions.  I usually use a Debug build
so I look for it at src/out/Debug/packager.  If you did Release build, I'm
sure it would be same path but under Release instead of Debug.

Garret

**Comment by dmfrey** [comment]
@thecount2a thanks. I copied it into there.  Does running `ffmpeg -version` indicate this is installed and active?

**Comment by thecount2a** [comment]
ffmpeg is often installed on linux platforms but linux distros have a habit
of keeping around older versions.  To take full advantage of commercial
cutting, I would suggest the latest static ffmpeg downloaded from
https://johnvansickle.com/ffmpeg/  Then you can copy the "ffmpeg" binary to
a directory with your "packager" binary and point the PHP script at that
directory.

If you want to run the ffmpeg that you have installed in your distro, look
carefully at the version and see if it is much older than 3.2 then
understand you may encounter problems with cutting commercials and other
little things like AAC audio encoding and properly encoding recordings that
may have gaps in them due to imperfect antenna reception from mythtv.   If
you do end up using your local distro's ffmpeg,  you can easily either
modify the source code of index.php to point at your distro's ffmpeg or
make a symlink to it.

Garret

**Comment by dmfrey** [comment]
I did use the one you recommended.  I was just trying to verify that ffmpeg
would recognize that new file in that directory is all.
